package server
import "net/http"
func(s *Server)dashboard(w http.ResponseWriter,r *http.Request){w.Header().Set("Content-Type","text/html; charset=utf-8");w.Write([]byte(dashHTML))}
const dashHTML=`<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Outpost</title>
<style>:root{--bg:#1a1410;--bg2:#241e18;--bg3:#2e261e;--rust:#c45d2c;--rl:#e8753a;--leather:#a0845c;--cream:#f0e6d3;--cd:#bfb5a3;--cm:#7a7060;--gold:#d4a843;--green:#4a9e5c;--red:#c44040;--mono:'JetBrains Mono',Consolas,monospace;--serif:'Libre Baskerville',Georgia,serif}*{margin:0;padding:0;box-sizing:border-box}body{background:var(--bg);color:var(--cream);font-family:var(--mono);font-size:13px;line-height:1.6}.hdr{padding:.6rem 1.2rem;border-bottom:1px solid var(--bg3);display:flex;justify-content:space-between;align-items:center}.hdr h1{font-family:var(--serif);font-size:1rem}.hdr h1 span{color:var(--rl)}.main{max-width:800px;margin:0 auto;padding:1rem}.overview{display:flex;gap:1.5rem;margin-bottom:1rem;font-size:.7rem;color:var(--leather)}.overview .stat b{display:block;font-size:1.4rem;color:var(--cream)}.host{background:var(--bg2);border:1px solid var(--bg3);padding:.7rem;margin-bottom:.4rem}.host-top{display:flex;align-items:center;gap:.6rem;margin-bottom:.4rem}.host-dot{width:10px;height:10px;border-radius:50%;flex-shrink:0}.host-dot.online{background:var(--green)}.host-dot.offline{background:var(--red)}.host-dot.unknown{background:var(--cm)}.host-name{font-weight:600;flex:1}.host-meta{font-size:.65rem;color:var(--cm);display:flex;gap:.7rem}.gauge{display:flex;gap:.8rem;margin-top:.3rem}.gauge-item{flex:1}.gauge-label{font-size:.6rem;color:var(--leather);text-transform:uppercase;margin-bottom:.15rem}.gauge-bar{height:5px;background:var(--bg3);border-radius:3px;overflow:hidden}.gauge-fill{height:100%;transition:width .3s}.gf-ok{background:var(--green)}.gf-warn{background:var(--gold)}.gf-crit{background:var(--red)}.gauge-val{font-size:.7rem;font-weight:600;margin-top:.1rem}.empty{text-align:center;padding:2rem;color:var(--cm);font-style:italic;font-family:var(--serif)}</style>
<link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville:ital@0;1&family=JetBrains+Mono:wght@400;600&display=swap" rel="stylesheet">
</head><body><div class="hdr"><h1><span>Outpost</span></h1><span style="font-size:.65rem;color:var(--cm)">POST /api/report</span></div>
<div class="main"><div id="upgrade-banner" style="display:none;background:#241e18;border:1px solid #8b3d1a;border-left:3px solid #c45d2c;padding:.6rem 1rem;font-size:.78rem;color:#bfb5a3;margin-bottom:.8rem"><strong style="color:#f0e6d3">Free tier</strong> — 10 items max. <a href="https://stockyard.dev/outpost/" target="_blank" style="color:#e8753a">Upgrade to Pro →</a></div><div class="overview" id="ov"></div><div id="list"></div></div>
<script>
async function api(u){return(await fetch(u)).json()}
function esc(s){return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
function timeAgo(d){if(!d)return'never';const s=Math.floor((Date.now()-new Date(d))/1e3);if(s<60)return s+'s ago';if(s<3600)return Math.floor(s/60)+'m ago';return Math.floor(s/3600)+'h ago'}
function gaugeCls(v){return v>=90?'gf-crit':v>=70?'gf-warn':'gf-ok'}
async function load(){const[sd,hd]=await Promise.all([api('/api/stats'),api('/api/hosts')]);
document.getElementById('ov').innerHTML='<div class="stat"><b>'+sd.total+'</b>Hosts</div><div class="stat"><b style="color:var(--green)">'+sd.online+'</b>Online</div><div class="stat"><b style="color:'+(sd.offline?'var(--red)':'var(--green)')+'">'+sd.offline+'</b>Offline</div>';
const hosts=hd.hosts||[];
document.getElementById('list').innerHTML=hosts.length?hosts.map(h=>
'<div class="host"><div class="host-top"><div class="host-dot '+h.status+'"></div><span class="host-name">'+esc(h.name)+'</span><span class="host-meta">'+esc(h.hostname)+(h.ip?' · '+esc(h.ip):'')+(h.os?' · '+esc(h.os):'')+'</span><span style="font-size:.6rem;color:var(--cm)">'+timeAgo(h.last_report)+'</span></div>'+
'<div class="gauge">'+
'<div class="gauge-item"><div class="gauge-label">CPU</div><div class="gauge-bar"><div class="gauge-fill '+gaugeCls(h.cpu_pct)+'" style="width:'+h.cpu_pct+'%"></div></div><div class="gauge-val" style="color:var(--'+(h.cpu_pct>=90?'red':h.cpu_pct>=70?'gold':'green')+')">'+h.cpu_pct.toFixed(0)+'%</div></div>'+
'<div class="gauge-item"><div class="gauge-label">Memory</div><div class="gauge-bar"><div class="gauge-fill '+gaugeCls(h.mem_pct)+'" style="width:'+h.mem_pct+'%"></div></div><div class="gauge-val" style="color:var(--'+(h.mem_pct>=90?'red':h.mem_pct>=70?'gold':'green')+')">'+h.mem_pct.toFixed(0)+'%</div></div>'+
'<div class="gauge-item"><div class="gauge-label">Disk</div><div class="gauge-bar"><div class="gauge-fill '+gaugeCls(h.disk_pct)+'" style="width:'+h.disk_pct+'%"></div></div><div class="gauge-val" style="color:var(--'+(h.disk_pct>=90?'red':h.disk_pct>=70?'gold':'green')+')">'+h.disk_pct.toFixed(0)+'%</div></div>'+
'</div></div>').join(''):'<div class="empty">No hosts reporting. Send metrics via POST /api/report</div>'}
load();setInterval(load,10000)
fetch('/api/tier').then(r=>r.json()).then(j=>{if(j.tier==='free'){var b=document.getElementById('upgrade-banner');if(b)b.style.display='block'}}).catch(()=>{var b=document.getElementById('upgrade-banner');if(b)b.style.display='block'});
</script></body></html>`
